package com.crawler.law.core;

import java.util.HashMap;
import java.util.Map;

public class ShareApplication {
    public static Map<String, String> CATEGORY_MAP = new HashMap<>();
    public static Map<String, String> AGENCY_MAP = new HashMap<>();
    public static Map<String, String> TYPE_MAP = new HashMap<>();

    static {
        CATEGORY_MAP.put("An ninh quốc gia","2");
        CATEGORY_MAP.put("Lao động","3");
        CATEGORY_MAP.put("Kế toán, kiểm toán","4");
        CATEGORY_MAP.put("Thuế, phí, lệ phí","5");
        CATEGORY_MAP.put("Thương mại, đầu tư, chứng khoán","6");
        CATEGORY_MAP.put("Doanh nghiệp, hợp tác xã","7");
        CATEGORY_MAP.put("Đất đai","8");
        CATEGORY_MAP.put("Môi trường","9");
        CATEGORY_MAP.put("Dân sự","10");
        CATEGORY_MAP.put("Hình sự","11");
        CATEGORY_MAP.put("Tài nguyên","12");
        CATEGORY_MAP.put("Công nghiệp","13");
        CATEGORY_MAP.put("Dân tộc","14");
        CATEGORY_MAP.put("Giáo dục, đào tạo","15");
        CATEGORY_MAP.put("Giao thông, vận tải","16");
        CATEGORY_MAP.put("Hành chính tư pháp","17");
        CATEGORY_MAP.put("Khiếu nại, tố cáo","18");
        CATEGORY_MAP.put("Khoa học, công nghệ","19");
        CATEGORY_MAP.put("Bảo hiểm","20");
        CATEGORY_MAP.put("Ngân hàng, tiền tệ","21");
        CATEGORY_MAP.put("Ngoại giao, điều ước quốc tế","22");
        CATEGORY_MAP.put("Nông nghiệp, nông thôn","23");
        CATEGORY_MAP.put("Quốc phòng","24");
        CATEGORY_MAP.put("Tài chính","25");
        CATEGORY_MAP.put("Tài sản công, nợ công, dự trữ nhà nước","26");
        CATEGORY_MAP.put("Thi đua, khen thưởng, các danh hiệu vinh dự nhà nước","27");
        CATEGORY_MAP.put("Thi hành án","28");
        CATEGORY_MAP.put("Thống kê","29");
        CATEGORY_MAP.put("Thông tin báo chí, xuất bản","30");
        CATEGORY_MAP.put("Bổ trợ tư pháp","31");
        CATEGORY_MAP.put("Tổ chức bộ máy nhà nước","32");
        CATEGORY_MAP.put("Tổ chức chính trị - xã hội","33");
        CATEGORY_MAP.put("Tố tụng và các phương thức giải quyết tranh chấp","34");
        CATEGORY_MAP.put("Tôn giáo, tín ngưỡng","35");
        CATEGORY_MAP.put("Trật tự an toàn xã hội","36");
        CATEGORY_MAP.put("Tương trợ tư pháp","37");
        CATEGORY_MAP.put("Văn hóa , thể thao, du lịch","38");
        CATEGORY_MAP.put("Văn thư, lưu trữ","39");
        CATEGORY_MAP.put("Xây dựng nhà ở, đô thị","40");
        CATEGORY_MAP.put("Bưu chính, viễn thông","41");
        CATEGORY_MAP.put("Xây dựng pháp luật và thi hành pháp luật","42");
        CATEGORY_MAP.put("Y tế - dược","43");
        CATEGORY_MAP.put("Cán bộ, công chức, viên chức","44");
        CATEGORY_MAP.put("Chính sách xã hội","45");
        CATEGORY_MAP.put("Dân số, trẻ em, gia đình, bình đẳng giới","46");
        CATEGORY_MAP.put("Lĩnh vực khác","47");

        AGENCY_MAP.put("Bảo hiểm xã hội Việt Nam","3");
        AGENCY_MAP.put("Bộ Công An","4");
        AGENCY_MAP.put("Bộ Công thương","5");
        AGENCY_MAP.put("Bộ Giáo dục và Đào tạo","6");
        AGENCY_MAP.put("Bộ Giao thông vận tải","7");
        AGENCY_MAP.put("Bộ Kế hoạch và Đầu tư","8");
        AGENCY_MAP.put("Bộ Khoa học và Công nghệ","9");
        AGENCY_MAP.put("Bộ Lao động – Thương binh và Xã hội","10");
        AGENCY_MAP.put("Bộ Ngoại giao","11");
        AGENCY_MAP.put("Bộ Nội vụ","12");
        AGENCY_MAP.put("Bộ Nông nghiệp và Phát triển nông thôn","13");
        AGENCY_MAP.put("Bộ Quốc phòng","14");
        AGENCY_MAP.put("Bộ Tài chính","15");
        AGENCY_MAP.put("Bộ Tài nguyên và Môi trường","16");
        AGENCY_MAP.put("Bộ Thông tin và Truyền thông","17");
        AGENCY_MAP.put("Bộ Tư pháp","18");
        AGENCY_MAP.put("Bộ Văn hoá, Thể thao và du lịch","19");
        AGENCY_MAP.put("Bộ Xây dựng","20");
        AGENCY_MAP.put("Bộ Y tế","21");
        AGENCY_MAP.put("Chính phủ","22");
        AGENCY_MAP.put("Chủ tịch nước","23");
        AGENCY_MAP.put("Kiểm toán Nhà nước","24");
        AGENCY_MAP.put("Ngân hàng Nhà nước","25");
        AGENCY_MAP.put("Quốc hội","26");
        AGENCY_MAP.put("Thanh tra Chính phủ","27");
        AGENCY_MAP.put("Thủ tướng Chính phủ","28");
        AGENCY_MAP.put("Tòa án nhân dân tối cao","29");
        AGENCY_MAP.put("Tổng cục Hải quan","30");
        AGENCY_MAP.put("Tổng cục Thuế","31");
        AGENCY_MAP.put("Tổng liên đoàn Lao động Việt Nam","32");
        AGENCY_MAP.put("Ủy ban Dân tộc","33");
        AGENCY_MAP.put("Ủy ban Thường vụ Quốc hội","34");
        AGENCY_MAP.put("Văn phòng Chính phủ","35");
        AGENCY_MAP.put("Viện kiểm sát nhân dân tối cao","36");
        AGENCY_MAP.put("Các cơ quan khác","37");
        AGENCY_MAP.put("Thành phố Cần Thơ","38");
        AGENCY_MAP.put("Thành phố Đà Nẵng","39");
        AGENCY_MAP.put("Thành phố Hà Nội","40");
        AGENCY_MAP.put("Thành phố Hải Phòng","41");
        AGENCY_MAP.put("Thành phố Hồ Chí Minh","42");
        AGENCY_MAP.put("Tỉnh An Giang","43");
        AGENCY_MAP.put("Tỉnh Bà Rịa - Vũng Tàu","44");
        AGENCY_MAP.put("Tỉnh Bắc Giang","45");
        AGENCY_MAP.put("Tỉnh Bắc Kạn","46");
        AGENCY_MAP.put("Tỉnh Bạc Liêu","47");
        AGENCY_MAP.put("Tỉnh Bắc Ninh","48");
        AGENCY_MAP.put("Tỉnh Bến Tre","49");
        AGENCY_MAP.put("Tỉnh Bình Định","50");
        AGENCY_MAP.put("Tỉnh Bình Dương","51");
        AGENCY_MAP.put("Tỉnh Bình Phước","52");
        AGENCY_MAP.put("Tỉnh Bình Thuận","53");
        AGENCY_MAP.put("Tỉnh Cà Mau","54");
        AGENCY_MAP.put("Tỉnh Cao Bằng","55");
        AGENCY_MAP.put("Tỉnh Đắk Lắk","56");
        AGENCY_MAP.put("Tỉnh Đắk Nông","57");
        AGENCY_MAP.put("Tỉnh Điện Biên","58");
        AGENCY_MAP.put("Tỉnh Đồng Nai","59");
        AGENCY_MAP.put("Tỉnh Đồng Tháp","60");
        AGENCY_MAP.put("Tỉnh Gia Lai","61");
        AGENCY_MAP.put("Tỉnh Hà Giang","62");
        AGENCY_MAP.put("Tỉnh Hà Nam","63");
        AGENCY_MAP.put("Tỉnh Hà Tĩnh","64");
        AGENCY_MAP.put("Tỉnh Hải Dương","65");
        AGENCY_MAP.put("Tỉnh Hậu Giang","66");
        AGENCY_MAP.put("Tỉnh Hòa Bình","67");
        AGENCY_MAP.put("Tỉnh Hưng Yên","68");
        AGENCY_MAP.put("Tỉnh Khánh Hòa","69");
        AGENCY_MAP.put("Tỉnh Kiên Giang","70");
        AGENCY_MAP.put("Tỉnh Kon Tum","71");
        AGENCY_MAP.put("Tỉnh Lai Châu","72");
        AGENCY_MAP.put("Tỉnh Lâm Đồng","73");
        AGENCY_MAP.put("Tỉnh Lạng Sơn","74");
        AGENCY_MAP.put("Tỉnh Lào Cai","75");
        AGENCY_MAP.put("Tỉnh Long An","76");
        AGENCY_MAP.put("Tỉnh Nam Định","77");
        AGENCY_MAP.put("Tỉnh Nghệ An","78");
        AGENCY_MAP.put("Tỉnh Ninh Bình","79");
        AGENCY_MAP.put("Tỉnh Ninh Thuận","80");
        AGENCY_MAP.put("Tỉnh Phú Thọ","81");
        AGENCY_MAP.put("Tỉnh Phú Yên","82");
        AGENCY_MAP.put("Tỉnh Quảng Bình","83");
        AGENCY_MAP.put("Tỉnh Quảng Nam","84");
        AGENCY_MAP.put("Tỉnh Quảng Ngãi","85");
        AGENCY_MAP.put("Tỉnh Quảng Ninh","86");
        AGENCY_MAP.put("Tỉnh Quảng Trị","87");
        AGENCY_MAP.put("Tỉnh Sóc Trăng","88");
        AGENCY_MAP.put("Tỉnh Sơn La","89");
        AGENCY_MAP.put("Tỉnh Tây Ninh","90");
        AGENCY_MAP.put("Tỉnh Thái Bình","91");
        AGENCY_MAP.put("Tỉnh Thái Nguyên","92");
        AGENCY_MAP.put("Tỉnh Thanh Hóa","93");
        AGENCY_MAP.put("Tỉnh Thừa Thiên Huế","94");
        AGENCY_MAP.put("Tỉnh Tiền Giang","95");
        AGENCY_MAP.put("Tỉnh Trà Vinh","96");
        AGENCY_MAP.put("Tỉnh Tuyên Quang","97");
        AGENCY_MAP.put("Tỉnh Vĩnh Long","98");
        AGENCY_MAP.put("Tỉnh Vĩnh Phúc","99");
        AGENCY_MAP.put("Tỉnh Yên Bái","100");

        TYPE_MAP.put("Chỉ thị","1");
        TYPE_MAP.put("Điều ước quốc tế","2");
        TYPE_MAP.put("Hiến pháp","3");
        TYPE_MAP.put("Lệnh","4");
        TYPE_MAP.put("Luật","5");
        TYPE_MAP.put("Nghị định","6");
        TYPE_MAP.put("Nghị quyết","7");
        TYPE_MAP.put("Pháp lệnh","8");
        TYPE_MAP.put("Quyết định","9");
        TYPE_MAP.put("Sắc lệnh","10");
        TYPE_MAP.put("Thông tư","11");
        TYPE_MAP.put("Thông tư liên tịch","12");
        TYPE_MAP.put("Văn bản hợp nhất","13");
        TYPE_MAP.put("Văn bản khác","14");
        TYPE_MAP.put("Văn bản WTO","15");
        TYPE_MAP.put("Quy chuẩn","16");
        TYPE_MAP.put("Công điện","17");
        TYPE_MAP.put("Công văn","18");
    }
}
